services:
  db:
    container_name: banking-dev
    image: postgres:latest
    environment:
      POSTGRES_USER: cfkiatong
      POSTGRES_PASSWORD: password
      POSTGRES_DB: banking_dev
      PGDATA: /data/postgres
    volumes:
      - banking-postgres-dev:/data/postgres
    ports:
      - "5532:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  banking-postgres-dev: